# Generated by Django 3.2.6 on 2022-01-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('1', '1st'), ('2', '2nd')], default=2, max_length=3),
        ),
        migrations.AddField(
            model_name='material',
            name='semester',
            field=models.CharField(choices=[('1', '1st'), ('2', '2nd')], default=2, max_length=3),
        ),
    ]
