# Generated by Django 3.2.6 on 2022-01-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20220125_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('1', '1st'), ('2', '2nd')], default=2, editable=False, max_length=3),
        ),
    ]
