# Generated by Django 3.2.6 on 2021-08-23 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20210819_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='material',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material', to='front.course'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='current_semester_time_table',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
