# Generated by Django 3.2.6 on 2021-08-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_auto_20210823_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_code',
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='No name', max_length=60),
            preserve_default=False,
        ),
    ]
